In [2]:
print ('name')

name


In [3]:
lst=list()

In [4]:
type(lst)

list

In [ ]:
lst

In [14]:
lst.append('Keisha')

In [15]:
lst

['Keisha']

In [16]:
lst.append('I will be successful')

In [17]:
lst

['Keisha', 'I will be successful']

In [18]:
str=lst[0]

In [19]:
str

'Keisha'

In [20]:
type(str)

str

In [21]:
str.isalpha()

True

In [23]:
lst.append('Me')

In [24]:
lst


['Keisha', 'I will be successful', 'Me']

In [25]:
lst[1:3]

['I will be successful', 'Me']

In [26]:
lst[1:2]

['I will be successful']

In [27]:
lst[1:]

['I will be successful', 'Me']

In [28]:
#insert fn

In [29]:
lst.insert(2,'Trees')

In [30]:
lst

['Keisha', 'I will be successful', 'Trees', 'Me']

In [31]:
lst.append(['Rash', 'Kalra']) #nested list 

In [32]:
lst

['Keisha', 'I will be successful', 'Trees', 'Me', ['Rash', 'Kalra']]

In [33]:
lst.extend([1,2])

In [34]:
lst

['Keisha', 'I will be successful', 'Trees', 'Me', ['Rash', 'Kalra'], 1, 2]

In [35]:
lst.append(1)

In [36]:
lst.count(1)

2

In [37]:
lst.index(1)

5

In [38]:
max(lst)

TypeError: '>' not supported between instances of 'list' and 'str'

In [39]:
lst*2

['Keisha',
 'I will be successful',
 'Trees',
 'Me',
 ['Rash', 'Kalra'],
 1,
 2,
 1,
 'Keisha',
 'I will be successful',
 'Trees',
 'Me',
 ['Rash', 'Kalra'],
 1,
 2,
 1]

In [40]:
import numpy as np

In [41]:
a=9

In [42]:
arr=np.array(a)

In [43]:
arr

array(9)

In [44]:
 type(arr)

numpy.ndarray

In [45]:
print(arr)

9


In [46]:
my_lst=[1,3,3,5,5]

In [50]:
er=np.array(my_lst)

In [48]:
print(arr)

9


In [51]:
print(er)

[1 3 3 5 5]


In [52]:
er


array([1, 3, 3, 5, 5])

In [53]:
my_lst1=[1,2,3,4,5]

In [54]:
my_lst2=[2,3,4,5,6]
my_lst3=[3,4,5,6,7]

In [55]:
orry=np.array([my_lst1,my_lst2,my_lst3])

In [56]:
orry

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [60]:
 orry.shape

(3, 5)

In [61]:
orry.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [63]:
# reshaping is changing dimensions of the given array 3x5 to 5x3

In [64]:
orry.reshape(3,5)

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [65]:
arr2=np.array([1,2,3,4,5 ])

In [66]:
arr3=np.array([2,3,4,5,6])

In [67]:
arr4=np.array([3,4,5,6,7])

In [68]:
orry2=np.array([arr2, arr3,arr4])

In [69]:
orry2


array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [70]:
orry2[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [71]:
orry2[0:4,0:3]

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [72]:
orry2[1:,2:]

array([[4, 5, 6],
       [5, 6, 7]])

In [74]:
arr2[3:]=100

In [75]:
arr2

array([  1,   2,   3, 100, 100])

In [76]:
val=2

arr2[arr2<3]

array([1, 2])

In [1]:
arr2[arr2<5]

NameError: name 'arr2' is not defined

In [78]:
arr

array(9)

In [79]:
np.linspace()

TypeError: linspace() missing 2 required positional arguments: 'start' and 'stop'

In [83]:
arr=np.arange(0,12,1)

In [84]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [85]:
arr=arr1

NameError: name 'arr1' is not defined

In [86]:
arr=arr2

In [87]:
arr

array([  1,   2,   3, 100, 100])

In [88]:
arr2[3:]=4

In [89]:
arr

array([1, 2, 3, 4, 4])

In [90]:
arr*2

array([2, 4, 6, 8, 8])

In [91]:
arr

array([1, 2, 3, 4, 4])

In [92]:
arr=arr2.copy()